#!/bin/bash

BCONFIG=Debug
VERSION=1.0.5

INSTALLDIR="/usr/local/lib"
MODULESDIR=$INSTALLDIR/libadbo-$VERSION/
mkdir $MODULESDIR

INCLUDEDIR=/usr/local/include/libadbo-$VERSION
mkdir $INCLUDEDIR

ENTCDIR=$(dirname $PWD)

cp $PWD/core/$BCONFIG/libadbo.dylib $INSTALLDIR/libadbo.$VERSION.dylib
install_name_tool -id $INSTALLDIR/libadbo.$VERSION.dylib $INSTALLDIR/libadbo.$VERSION.dylib

mkdir $INCLUDEDIR
rm $INCLUDEDIR/*
cp $PWD/core/*.h $INCLUDEDIR/
