#!/bin/bash

BCONFIG=Debug
VERSION=1.0.5

INSTALLDIR="/usr/lib"
MODULESDIR=$INSTALLDIR/libadbl-$VERSION/
mkdir $MODULESDIR

INCLUDEDIR="/usr/include/libadbl-"$VERSION
mkdir $INCLUDEDIR

cp $PWD/core/libadbl.so $INSTALLDIR/libadbl.so.$VERSION

rm $INSTALLDIR/libadbl.so
ln -s $INSTALLDIR/libadbl.so.$VERSION $INSTALLDIR/libadbl.so

cp $PWD/adbl_sqlite/libadbl_sqlite3.so $MODULESDIR
cp $PWD/adbl_mysql/libadbl_mysql.so $MODULESDIR

rm $INCLUDEDIR/*
cp $PWD/core/*.h $INCLUDEDIR/
